In [38]:
import pandas as pd
import librosa
import numpy as np
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [39]:
df = pd.read_csv('../data/labels/bnd_voices.csv')
df.head()

              song start  finish   member
0  dear_my_darling   0:08   0:22   Sungho
1  dear_my_darling   0:23   0:36    Riwoo
2  dear_my_darling   0:37   0:51  Jaehyun
3  dear_my_darling   0:52   1:07  Woonhak
4  dear_my_darling   1:08   1:20   Leehan

In [40]:
df.dtypes

song      str
start     str
finish    str
member    str
dtype: object

In [41]:
def convert_to_seconds(time_str):
    parts = time_str.split(":")
    minutes = int(parts[0])
    seconds = int(parts[1])
    total = minutes * 60 + seconds
    return total

convert_to_seconds("1:20")

80

In [42]:
df.columns = df.columns.str.strip()
df.columns
df["start_sec"] = df["start"].apply(convert_to_seconds)
df["finish_sec"] = df["finish"].apply(convert_to_seconds)
df.head()

              song start finish   member  start_sec  finish_sec
0  dear_my_darling  0:08   0:22   Sungho          8          22
1  dear_my_darling  0:23   0:36    Riwoo         23          36
2  dear_my_darling  0:37   0:51  Jaehyun         37          51
3  dear_my_darling  0:52   1:07  Woonhak         52          67
4  dear_my_darling  1:08   1:20   Leehan         68          80

In [43]:
import soundfile as sf

In [44]:
for index, row in df.iterrows():
    print(row["song"], row["start_sec"], row["finish_sec"], row["member"])

dear_my_darling 8 22 Sungho
dear_my_darling 23 36 Riwoo
dear_my_darling 37 51 Jaehyun
dear_my_darling 52 67 Woonhak
dear_my_darling 68 80 Leehan
dear_my_darling 81 97 Taesan
123_78_ 14 20 Jaehyun
123_78_ 21 27 Leehan
123_78_ 28 37 Sungho
123_78_ 38 42 Riwoo
123_78_ 43 44 Leehan
123_78_ 45 51 Woonhak
123_78_ 52 58 Taesan
123_78_ 59 70 Riwoo
123_78_ 71 79 Woonhak
123_78_ 80 83 Jaehyun
123_78_ 84 93 Sungho
123_78_ 94 97 Leehan
123_78_ 98 100 Jaehyun
123_78_ 101 107 Riwoo
123_78_ 108 114 Taesan
123_78_ 115 125 Jaehyun
123_78_ 143 149 Leehan
123_78_ 150 155 Sungho
reality 21 184 Taesan
iktoy 13 140 Taesan
smart 8 73 Jaehyun
sway 15 108 Leehan
ttte 8 60 Sungho
winner 0 83 Woonhak
darling 8 74 Riwoo

itterrows used

In [45]:
unique_songs = df["song"].unique()

for song_name in unique_songs:
    y,sr = librosa.load(f"../data/raw_audio/{song_name}.mp3", sr=None)
    song_rows = df[df["song"]==song_name]
    for index, row in song_rows.iterrows():
        start_sample = int(row["start_sec"] * sr)
        end_sample = int(row["finish_sec"] * sr)
        clip = y[start_sample:end_sample]
        sf.write(f"../data/processed/{row['member']}_{index}.wav", clip, sr)

In [46]:
def extract_features(file_path):
    y, sr = librosa.load(file_path, sr=None)
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    mfcc_mean = mfcc.mean(axis=1)
    mfcc_std = mfcc.std(axis=1)
    feature_vector = np.concatenate([mfcc_mean, mfcc_std])
    return feature_vector

test_features = extract_features("../data/processed/Sungho_0.wav")
print(test_features.shape)

(26,)

In [47]:
folder_path = "../data/processed/"
all_files = os.listdir(folder_path)
print(all_files)

['Jaehyun_15.wav', 'Jaehyun_18.wav', 'Jaehyun_2.wav', 'Jaehyun_21.wav', 'Jaehyun_26.wav', 'Jaehyun_6.wav', 'Leehan_10.wav', 'Leehan_17.wav', 'Leehan_22.wav', 'Leehan_27.wav', 'Leehan_4.wav', 'Leehan_7.wav', 'Riwoo_1.wav', 'Riwoo_13.wav', 'Riwoo_19.wav', 'Riwoo_30.wav', 'Riwoo_9.wav', 'Sungho_0.wav', 'Sungho_16.wav', 'Sungho_23.wav', 'Sungho_28.wav', 'Sungho_8.wav', 'Taesan_12.wav', 'Taesan_20.wav', 'Taesan_24.wav', 'Taesan_25.wav', 'Taesan_5.wav', 'test', 'train', 'Woonhak_11.wav', 'Woonhak_14.wav', 'Woonhak_29.wav', 'Woonhak_3.wav']

Test faylinin organize edilmesi

In [48]:
df_test = pd.read_csv("../data/labels/bnd_voices_test.csv")
df_test.columns = df_test.columns.str.strip()
df_test.head()

        song start finish   member
0  dangerous  0:08   0:17   Taesan
1  dangerous  0:18   0:25   Leehan
2  dangerous  0:26   0:33  Woonhak
3  dangerous  0:34   0:42  Jaehyun
4  dangerous  0:44   0:51   Sungho

In [49]:
df_test["start_sec"] = df_test["start"].apply(convert_to_seconds)
df_test["finish_sec"] = df_test["finish"].apply(convert_to_seconds)
df_test.head()

        song start finish   member  start_sec  finish_sec
0  dangerous  0:08   0:17   Taesan          8          17
1  dangerous  0:18   0:25   Leehan         18          25
2  dangerous  0:26   0:33  Woonhak         26          33
3  dangerous  0:34   0:42  Jaehyun         34          42
4  dangerous  0:44   0:51   Sungho         44          51

In [50]:
y, sr = librosa.load("../data/raw_audio/dangerous.mp3", sr=None)

for index, row in df_test.iterrows():
    start_sample = int(row["start_sec"] * sr)
    end_sample = int(row["finish_sec"] * sr)
    clip = y[start_sample:end_sample]
    sf.write(f"../data/processed/test/{row['member']}_{index}.wav", clip, sr)

Train

In [51]:
train_folder = "../data/processed/train/"
train_files = os.listdir(train_folder)

X_train_list = []
y_train_list = []

for filename in train_files:
    member_name = filename.split("_")[0]
    y_train_list.append(member_name)
    
    file_path = train_folder + filename
    features = extract_features(file_path)
    X_train_list.append(features)

X_train = np.array(X_train_list)
y_train = np.array(y_train_list)

print(X_train.shape)
print(y_train.shape)

(31, 26)
(31,)

In [52]:
print(set(y_train))
from collections import Counter
print(Counter(y_train))

{np.str_('Riwoo'), np.str_('Leehan'), np.str_('Sungho'), np.str_('Taesan'), np.str_('Woonhak'), np.str_('Jaehyun')}
Counter({np.str_('Jaehyun'): 6, np.str_('Leehan'): 6, np.str_('Riwoo'): 5, np.str_('Sungho'): 5, np.str_('Taesan'): 5, np.str_('Woonhak'): 4})

Test

In [53]:
test_folder = "../data/processed/test/"
test_files = os.listdir(test_folder)

X_test_list = []
y_test_list = []

for filename in test_files:
    member_name = filename.split("_")[0]
    y_test_list.append(member_name)
    
    file_path = test_folder + filename
    features = extract_features(file_path)
    X_test_list.append(features)

X_test = np.array(X_test_list)
y_test = np.array(y_test_list)

print(X_test.shape)
print(y_test.shape)
print(set(y_test))

(14, 26)
(14,)
{np.str_('Riwoo'), np.str_('Leehan'), np.str_('Sungho'), np.str_('Taesan'), np.str_('Woonhak'), np.str_('Jaehyun')}

In [54]:
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

changed k 3 to 8 bcs of distance between test and training data error

In [55]:
from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2%}")

Accuracy: 28.57%

In [56]:
print(confusion_matrix(y_test, y_pred, labels=list(set(y_test))))
print(list(set(y_test)))

[[2 0 0 0 0 0]
 [0 0 0 0 0 2]
 [0 0 0 0 0 2]
 [0 0 0 0 0 3]
 [0 0 0 0 0 2]
 [1 0 0 0 0 2]]
[np.str_('Riwoo'), np.str_('Leehan'), np.str_('Sungho'), np.str_('Taesan'), np.str_('Woonhak'), np.str_('Jaehyun')]

In [57]:
print(X_train)

[[-7.12893982e+01  1.38887894e+02 -4.20865250e+01  6.05884933e+01
  -2.15031300e+01  3.59917717e+01 -1.48545790e+01  1.23755646e+01
  -8.86124325e+00  3.96411896e+00 -1.92983007e+00 -1.90751183e+00
   4.67735815e+00  5.38991966e+01  3.33425980e+01  1.86704006e+01
   2.08214951e+01  1.95451527e+01  1.31402588e+01  1.32126236e+01
   9.28304672e+00  1.25759850e+01  9.74850273e+00  9.10390472e+00
   8.01821041e+00  7.95010138e+00]
 [-1.02488045e+02  1.33703369e+02 -4.05562325e+01  5.82842751e+01
  -1.30726662e+01  3.84795265e+01 -8.09820271e+00  1.63662434e+01
  -3.86690521e+00  5.63466978e+00  5.40942669e+00  5.06215191e+00
   9.03415966e+00  5.84836693e+01  2.62224712e+01  2.54620876e+01
   1.61099072e+01  2.54506073e+01  1.98607540e+01  1.69729977e+01
   1.02883997e+01  1.06092472e+01  1.08205328e+01  9.58785057e+00
   9.07210922e+00  8.04514885e+00]
 [-8.64342575e+01  1.58733551e+02 -2.23159523e+01  3.64354591e+01
  -3.08516884e+01  2.63069668e+01 -8.43927860e+00  8.53743649e+00
  -1.06384153e+01 -1.07830875e-01  2.07086182e+00  8.84808064e-01
   6.23968220e+00  4.70477333e+01  2.50372467e+01  1.51766577e+01
   2.07671776e+01  1.89465675e+01  1.31665297e+01  8.52323055e+00
   1.05774851e+01  8.92950821e+00  8.74170113e+00  8.17044067e+00
   7.94547367e+00  7.33088636e+00]
 [-5.56035118e+01  1.55646973e+02 -3.98533554e+01  5.77553749e+01
  -2.98752022e+01  2.59906216e+01 -1.07752180e+01  1.31602345e+01
  -5.79187679e+00  3.01116467e+00 -2.26165295e+00  6.92108631e-01
   5.76642466e+00  4.17087669e+01  2.46273041e+01  1.61054153e+01
   1.47873297e+01  1.68885021e+01  1.13878574e+01  1.36482277e+01
   9.14815521e+00  9.65705776e+00  7.74892902e+00  7.75237465e+00
   6.54217100e+00  8.13774776e+00]
 [-1.55891983e+02  1.34325409e+02 -2.62686939e+01  4.81350136e+01
  -3.04686775e+01  3.46352882e+01 -1.15626898e+01  8.31793880e+00
  -2.41827637e-01  5.49204731e+00  9.40026879e-01 -1.91666031e+00
   6.49053812e+00  4.67823296e+01  2.56726398e+01  1.97587910e+01
   2.39525967e+01  1.76594563e+01  1.52588377e+01  1.28714361e+01
   1.57638531e+01  1.15267344e+01  1.19493465e+01  1.03383808e+01
   1.06964159e+01  1.01235733e+01]
 [-1.22331467e+02  1.33116714e+02 -3.35656128e+01  5.08670921e+01
  -3.14763451e+01  2.46241570e+01 -1.55376482e+01  9.52745342e+00
  -1.02436934e+01  2.48028421e+00 -2.78235316e+00 -1.68573534e+00
   2.74284768e+00  5.70896530e+01  4.00884705e+01  2.48442440e+01
   2.08721561e+01  1.88788605e+01  1.50420523e+01  1.70153694e+01
   1.19909019e+01  1.26640406e+01  1.00444136e+01  9.76657295e+00
   9.25416565e+00  8.49206161e+00]
 [-1.20286995e+02  1.49682922e+02 -3.96763077e+01  6.18348541e+01
  -1.27563095e+01  4.28521080e+01 -7.96461153e+00  2.08964138e+01
  -4.82680798e+00  2.11948538e+00  6.73082256e+00 -8.90024185e-01
   1.10525732e+01  6.29718094e+01  2.90302277e+01  2.50045738e+01
   2.02470627e+01  2.30558033e+01  1.97088833e+01  1.30665894e+01
   9.80866432e+00  9.03036785e+00  1.14950666e+01  1.16692019e+01
   9.50488186e+00  9.05251408e+00]
 [-7.56211395e+01  1.50950989e+02 -3.05852985e+01  6.32594566e+01
  -3.02721710e+01  2.70698643e+01 -1.07650499e+01  9.13472652e+00
  -9.14655745e-01  2.52135468e+00 -4.09889030e+00  3.82459235e+00
   7.76580048e+00  4.49826126e+01  2.57344494e+01  2.02826023e+01
   1.38900480e+01  1.34363728e+01  1.21701765e+01  1.04137049e+01
   1.25117264e+01  8.39918041e+00  8.74062538e+00  8.54977989e+00
   8.58909988e+00  8.42860603e+00]
 [-4.62422142e+01  1.59710236e+02 -4.14766197e+01  5.95702744e+01
  -3.34514389e+01  2.76098518e+01 -9.08404446e+00  1.24081230e+01
  -3.89449763e+00  1.61251533e+00 -6.10020256e+00  1.97651815e+00
   7.44359684e+00  3.35182800e+01  2.34072170e+01  1.51128702e+01
   1.49487734e+01  1.43672276e+01  1.03607635e+01  8.96489716e+00
   8.70247936e+00  7.84739494e+00  7.55184650e+00  7.87640238e+00
   8.38652039e+00  7.40328407e+00]
 [-2.05713776e+02  1.57234650e+02 -1.29626141e+01  3.67582626e+01
  -1.21600885e+01  1.80368786e+01 -1.20140619e+01  2.16253257e+00
  -1.15129452e+01  1.62830067e+00 -1.15900974e+01  1.39281869e+00
  -3.58807039e+00  4.99356308e+01  2.97583485e+01  2.07098103e+01
   1.71575623e+01  1.46422358e+01  1.37920856e+01  1.07005262e+01
   1.28174162e+01  1.03768339e+01  9.82542324e+00  9.61458111e+00
   9.66442490e+00  8.76534176e+00]
 [-1.07108238e+02  1.72844849e+02 -9.77027416e+00  4.12246742e+01
  -1.83445358e+01  1.65617580e+01 -1.01726732e+01 -2.05108595e+00
  -9.30112267e+00  1.28596878e+00 -5.15560484e+00 -1.47183865e-01
   2.89998031e+00  4.85639648e+01  2.46927643e+01  1.83627052e+01
   1.91885242e+01  1.54210243e+01  1.31935577e+01  9.17119217e+00
   1.16464243e+01  1.02303791e+01  1.01600103e+01  8.49660015e+00
   7.37393236e+00  7.86426449e+00]
 [-8.95005035e+01  1.49421661e+02 -4.01017876e+01  4.95989418e+01
  -3.17593079e+01  2.28463039e+01 -1.44364500e+01  2.32025933e+00
  -3.31189013e+00  1.29601991e+00 -7.20244598e+00 -3.31827354e+00
   3.29975796e+00  4.74152107e+01  3.58367195e+01  1.88931828e+01
   2.06263103e+01  1.59971952e+01  1.47544661e+01  1.37197456e+01
   1.51476536e+01  1.18319016e+01  8.92994022e+00  1.08823290e+01
   9.96042919e+00  1.07350607e+01]
 [-1.10382896e+02  1.60217545e+02 -1.06375170e+01  2.46474018e+01
  -2.93098774e+01  3.06369038e+01 -6.00741816e+00  6.16749811e+00
  -1.38437014e+01  5.57172537e-01  2.21940136e+00 -4.44264364e+00
   6.99461269e+00  5.35027275e+01  2.75707798e+01  2.73378239e+01
   2.25133152e+01  1.87039909e+01  1.51296597e+01  1.49532127e+01
   9.88008881e+00  1.03097801e+01  9.67648125e+00  7.66116619e+00
   8.50633430e+00  7.70932198e+00]
 [-5.71674995e+01  1.59162216e+02 -4.32653618e+01  5.64835587e+01
  -3.11084652e+01  2.74696999e+01 -9.93837547e+00  1.13523731e+01
  -6.08343554e+00  2.44040298e+00 -1.54622400e+00 -1.61507416e+00
   8.56344509e+00  4.12410049e+01  2.40764656e+01  1.67727661e+01
   1.39768305e+01  1.54709902e+01  1.32719336e+01  1.39787951e+01
   1.02395792e+01  8.95180416e+00  7.72209024e+00  7.34057045e+00
   6.93694687e+00  7.52137804e+00]
 [-4.26679153e+01  1.52980576e+02 -4.18173561e+01  5.90571213e+01
  -3.50462837e+01  3.34741669e+01 -1.20023317e+01  1.43089828e+01
  -4.96962070e+00  5.91172028e+00 -2.39862502e-01 -1.97854757e+00
   7.23692226e+00  3.15532780e+01  1.79845905e+01  1.77989388e+01
   1.26826010e+01  1.00598431e+01  1.03273315e+01  9.09706306e+00
   7.27930641e+00  7.00077915e+00  8.43518734e+00  7.56696558e+00
   6.78478479e+00  7.06570911e+00]
 [-1.36198456e+02  1.74368134e+02 -2.40646815e+00  2.31529484e+01
  -1.14477472e+01  2.42437000e+01 -3.37333989e+00  3.04892564e+00
   8.31470299e+00 -2.22676086e+00  5.77058172e+00  2.40945721e+00
   8.80937767e+00  8.08345718e+01  2.28657761e+01  3.49134293e+01
   2.21320763e+01  1.79273357e+01  1.43339825e+01  1.34228621e+01
   1.07412014e+01  9.74480629e+00  9.21828365e+00  8.01639366e+00
   8.90195942e+00  8.19766331e+00]
 [-6.95176773e+01  1.53334595e+02 -3.02935371e+01  5.49457359e+01
  -3.53643799e+01  3.38636818e+01 -1.04019060e+01  1.17093048e+01
  -4.32441282e+00  1.57748950e+00 -1.02070403e+00  2.22610140e+00
   8.21754265e+00  4.04825439e+01  2.28551273e+01  1.97082958e+01
   1.24854736e+01  1.67226295e+01  1.10382090e+01  1.16570864e+01
   1.19738483e+01  8.77083397e+00  9.77691460e+00  7.51734352e+00
   8.27078342e+00  7.38885117e+00]
 [-1.88053116e+02  1.90234161e+02  1.23654187e+00  7.03718042e+00
  -1.77221737e+01  1.87965107e+01 -1.43657303e+01  1.23820257e+01
  -1.48421402e+01 -8.83929634e+00  3.47230887e+00 -2.52999783e+00
   2.75002390e-01  5.62949600e+01  3.31816483e+01  2.37692947e+01
   2.47533531e+01  1.49556036e+01  1.38323784e+01  1.60440903e+01
   1.38993959e+01  1.04505911e+01  7.84489107e+00  8.90498924e+00
   9.32060814e+00  8.03485107e+00]
 [-6.88138504e+01  1.68947968e+02 -3.74589233e+01  5.86261787e+01
  -2.53718948e+01  2.99134483e+01 -6.60514402e+00  1.05505953e+01
   1.41290832e+00  1.30887961e+00  1.36304760e+00 -8.83105576e-01
   5.93312550e+00  4.67790947e+01  2.23524590e+01  1.73555222e+01
   1.67621708e+01  1.15971880e+01  9.57891941e+00  1.01443253e+01
   8.62115574e+00  8.62351131e+00  8.13117599e+00  7.61380863e+00
   6.47204828e+00  7.05166578e+00]
 [-8.44188995e+01  1.60257645e+02 -4.03734131e+01  5.56956787e+01
  -2.52027111e+01  2.49213696e+01 -1.16895437e+01  2.68211818e+00
  -5.65426350e+00  1.62815261e+00 -2.76831007e+00 -5.51267910e+00
   5.06056261e+00  4.20537872e+01  2.52000580e+01  1.63070068e+01
   1.36953602e+01  1.47163143e+01  1.10226765e+01  1.39569178e+01
   9.70300198e+00  8.46652031e+00  8.38016987e+00  6.78454065e+00
   9.72462177e+00  8.55126190e+00]
 [-1.19940140e+02  1.47400818e+02 -2.90078278e+01  4.39131317e+01
  -1.59404097e+01  2.97373295e+01 -2.12199783e+01  1.11431055e+01
  -7.07023048e+00  1.26821613e+00 -5.47859144e+00  4.05740166e+00
  -2.14715767e+00  9.06526108e+01  3.47390747e+01  2.35869808e+01
   2.31809368e+01  1.81743584e+01  1.47823782e+01  1.36074276e+01
   1.30264778e+01  1.00537424e+01  1.27484074e+01  9.57421684e+00
   1.12915382e+01  9.31593227e+00]
 [-6.92518311e+01  1.70452515e+02 -3.57995224e+01  5.84646339e+01
  -2.70203800e+01  2.67196655e+01 -6.40962267e+00  1.02121143e+01
   1.12285459e+00  6.28112257e-01  8.19962084e-01 -1.84811497e+00
   4.82706642e+00  4.60731468e+01  2.68464222e+01  1.76455307e+01
   1.60854988e+01  1.28071012e+01  8.94640160e+00  9.91051483e+00
   9.24434090e+00  8.57744884e+00  7.78074694e+00  7.76202631e+00
   6.74113607e+00  6.93252039e+00]
 [-4.72483864e+01  1.63627655e+02 -4.32062035e+01  5.29877510e+01
  -3.18214149e+01  2.84184151e+01 -1.17983522e+01  1.40862627e+01
  -3.92010117e+00  7.78331137e+00 -1.55092895e+00 -1.32518843e-01
   6.75193501e+00  3.56376305e+01  2.07578278e+01  1.69773941e+01
   1.46716757e+01  1.15139637e+01  8.96788692e+00  1.11592760e+01
   8.84873295e+00  8.13914299e+00  7.16362190e+00  7.64918804e+00
   6.35339594e+00  6.03071594e+00]
 [-4.85402412e+01  1.63100739e+02 -4.18454208e+01  5.32572021e+01
  -3.16486568e+01  2.92806740e+01 -1.18204880e+01  1.47495518e+01
  -4.77879620e+00  7.62336349e+00 -1.77085245e+00 -2.79792577e-01
   7.06841326e+00  3.62456131e+01  2.14189644e+01  1.67634087e+01
   1.44989176e+01  1.19251776e+01  8.70344734e+00  1.13875351e+01
   8.20244980e+00  8.31437206e+00  7.48413610e+00  6.91042089e+00
   7.04934835e+00  6.12242270e+00]
 [-2.70619720e+02  1.87156235e+02  5.86936998e+00  7.76735067e+00
   1.96245098e+00  9.02987957e+00 -2.77664399e+00 -1.53679657e+01
  -6.97280526e-01 -5.52416229e+00 -6.62901306e+00 -8.66095829e+00
  -1.01329002e+01  6.38745003e+01  2.60976543e+01  3.54078636e+01
   2.43604412e+01  1.64474258e+01  1.12742519e+01  1.02141266e+01
   1.28858871e+01  9.63835812e+00  8.33775616e+00  9.16846752e+00
   8.18020248e+00  7.95462704e+00]
 [-1.47324127e+02  1.52174515e+02 -1.92445545e+01  5.02266312e+01
  -1.72001896e+01  3.09624443e+01 -1.70396252e+01  6.79478979e+00
  -3.94933558e+00  7.59429836e+00 -3.90694594e+00  4.25288773e+00
   2.43873191e+00  4.97003708e+01  2.57933464e+01  1.74956074e+01
   2.14362526e+01  1.63193932e+01  1.07541666e+01  1.12643013e+01
   1.07727146e+01  1.12288990e+01  8.93828583e+00  8.88703918e+00
   8.04383373e+00  7.12762594e+00]
 [-7.85598907e+01  1.64187943e+02 -2.83473282e+01  3.14142208e+01
  -2.31510868e+01  2.81022701e+01 -1.54334326e+01  6.35317850e+00
  -5.80322218e+00  3.46335244e+00 -1.22578883e+00 -8.11546206e-01
   5.30636835e+00  4.42102890e+01  2.39515476e+01  2.01218395e+01
   1.57894459e+01  1.58065186e+01  1.42331762e+01  1.16331749e+01
   1.10692701e+01  8.71032619e+00  8.22902107e+00  6.74183750e+00
   7.89449549e+00  7.33837986e+00]
 [-4.31838303e+01  1.59554626e+02 -4.61518745e+01  5.16810913e+01
  -3.25872841e+01  3.50797081e+01 -1.28216991e+01  1.33343678e+01
  -3.32942128e+00  7.17284727e+00 -9.85528290e-01 -1.46996665e+00
   7.71179152e+00  3.13161755e+01  1.89295845e+01  1.63209114e+01
   1.63864689e+01  1.17334213e+01  8.98775387e+00  1.03693514e+01
   7.90491295e+00  7.43217230e+00  8.17749596e+00  7.94496489e+00
   6.82278299e+00  6.11656570e+00]
 [-1.27213791e+02  1.47215302e+02 -3.36518517e+01  4.92681122e+01
  -7.12791109e+00  2.88971176e+01 -4.33073854e+00  8.83775520e+00
  -1.29181683e+00  2.83070898e+00 -2.56620145e+00 -1.94446898e+00
   3.68015099e+00  9.36320038e+01  3.39493790e+01  3.35733261e+01
   2.20542965e+01  2.58105087e+01  1.67120438e+01  1.61272411e+01
   1.20619516e+01  1.21708460e+01  9.61147118e+00  9.66452503e+00
   8.56192398e+00  8.89718819e+00]
 [-1.20245087e+02  1.31981354e+02 -3.42867889e+01  4.81497459e+01
  -6.70122480e+00  3.65367508e+01 -8.16768360e+00  1.51292238e+01
  -1.33861971e+00  7.80325699e+00 -2.51575947e+00  9.02141094e+00
   5.37461424e+00  7.22958603e+01  3.70041771e+01  1.89710064e+01
   2.19874992e+01  2.12338924e+01  1.48217211e+01  1.79529133e+01
   1.37102051e+01  1.44209833e+01  1.19998312e+01  1.12061949e+01
   9.91770458e+00  9.65216446e+00]
 [-1.08150085e+02  1.61960464e+02 -1.57638197e+01  4.14253159e+01
  -2.76463089e+01  2.45931568e+01 -7.39846468e+00  1.66980815e+00
  -2.93766284e+00 -7.54255295e+00 -4.90545034e-01 -5.75000906e+00
   1.17310897e-01  3.63175354e+01  2.14778709e+01  1.87396011e+01
   1.75047493e+01  1.45954924e+01  1.42157040e+01  7.46041679e+00
   1.22441254e+01  8.61585712e+00  8.79541779e+00  7.18600750e+00
   8.76755619e+00  9.51142120e+00]]

Comparing
train_accuracies = []
test_accuracies = []
k_values = range(1, 11)

for k in k_values:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    
    y_train_pred = model.predict(X_train)
    train_acc = accuracy_score(y_train, y_train_pred)
    train_accuracies.append(train_acc)
    
    y_test_pred = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_test_pred)
    test_accuracies.append(test_acc)

print("Train:", train_accuracies)
print("Test:", test_accuracies)

import matplotlib.pyplot as plt

plt.plot(k_values, train_accuracies, marker='o', label='Train Accuracy')
plt.plot(k_values, test_accuracies, marker='o', label='Test Accuracy')
plt.xlabel("n_neighbors (k)")
plt.ylabel("Accuracy")
plt.title("kNN: Train vs Test Accuracy")
plt.legend()
plt.grid(True)
plt.show()